apiVersion: v1
kind: Service
metadata:
  name: app-service # The load balancer will send traffic to this service
spec:
  selector:
    app: express-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

