apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3 # Run three pods for the API for high availability and load balancing
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend
        # IMPORTANT: Replace this with the backend image you build
        image: lalalapowa/hostnetix-backend:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # The port your Express app listens on
        env:
        - name: POSTGRES_HOST
          value: db # The name of the PostgreSQL service
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

