apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer-service
spec:
  # Use LoadBalancer for cloud environments or NodePort for local (e.g., Docker Desktop)
  type: LoadBalancer 
  selector:
    app: nginx-lb
  ports:
    - protocol: TCP
      port: 8080 # The external port you will connect to
      targetPort: 80 # The port on the NGINX pod

