apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-load-balancer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lb
  template:
    metadata:
      labels:
        app: nginx-lb
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf # Mounts only the nginx.conf key from the ConfigMap
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-load-balancer-config

