apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-load-balancer-config
data:
  nginx.conf: |
    events {}
    http {
        upstream express_servers {
            # This now points to the Kubernetes service for the app
            # Kubernetes DNS will automatically load balance across all 3 pods
            server app-service:8080;
        }

        server {
            listen 80;
            location / {
                proxy_pass http://express_servers;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
        }
    }

