apiVersion: v1
kind: Service
metadata:
  name: db # Named 'db' to match the POSTGRES_HOST env var
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

