apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  # Using stringData is convenient as it doesn't require base64 encoding.
  # These values match the docker-compose environment.
  POSTGRES_PASSWORD: "mypassword"

